

'use client';
import {useState,useRef,useEffect,useCallback} from 'react';
import {Box,Layers3,MoveUpRight,Scan,Footprints,RotateCcw,Download,Check,LockKeyhole,X,FileImage,Ruler,ArrowUp,ArrowDown,ArrowLeft,ArrowRight,Maximize2,PanelLeftClose,PanelLeftOpen,Info} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
import {Dialog,DialogContent,DialogTitle} from '@/components/ui/dialog';
import {rooms,walls,openings,columns,furniture,footprint,routes,assumptions,SCALE,SOURCE,type Point} from '@/lib/spatial/plan';
import type {ViewerAPI,ViewMode,ViewerOptions} from '@/lib/spatial/viewer';
const MODES:{id:ViewMode;title:string;label:string;icon:typeof Box}[]=[{id:'perspective',title:'3D Perspective',label:'透视',icon:Box},{id:'axon',title:'Axonometric',label:'轴测',icon:Layers3},{id:'top',title:'Top / Plan View',label:'俯视',icon:Scan},{id:'plan',title:'2D Floor Plan',label:'平面',icon:FileImage},{id:'walk',title:'First-person Walkthrough',label:'漫游',icon:Footprints}];
const INITIAL:ViewerOptions={furniture:true,ceiling:false,labels:true,routes:false,doors:true,cut:2.8};
export default function Home(){
 const host=useRef<HTMLDivElement>(null),api=useRef<ViewerAPI|null>(null);
 const [mode,setMode]=useState<ViewMode>('perspective'),[opts,setOpts]=useState(INITIAL),[ready,setReady]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState(''),[analysis,setAnalysis]=useState(false),[sidebar,setSidebar]=useState(true),[message,setMessage]=useState(''),[source,setSource]=useState(false),[overlay,setOverlay]=useState(0),[exporting,setExporting]=useState(false);
 const current=rooms.find(r=>r.id===selected),onSelect=useCallback((id:string)=>setSelected(id),[]);
 useEffect(()=>{let dead=false;import('@/lib/spatial/viewer').then(({createViewer})=>{if(dead||!host.current)return;api.current=createViewer(host.current,onSelect);setReady(true)}).catch(e=>setError('3D 初始化未完成：'+e.message+'。可切换到 2D 平面检查。'));return()=>{dead=true;api.current?.dispose();api.current=null}},[onSelect]);
 useEffect(()=>{api.current?.setMode(mode)},[mode,ready]);useEffect(()=>{api.current?.setOptions(opts)},[opts,ready]);
 const stateRef=useRef({mode,opts,selected,ready});stateRef.current={mode,opts,selected,ready};
 useEffect(()=>{
  type Context={registerTool:(t:{name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown},o:{signal:AbortSignal})=>void|Promise<void>};
  const context=(document as Document&{modelContext?:Context}).modelContext;if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const read={name:'read_spatial_model',description:'Read the current BASE view, layer visibility, room relationships and scale assumptions.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...stateRef.current,rooms:rooms.map(r=>({id:r.id,name:r.name,connects:r.connects})),source:SOURCE,assumptions})};
  const configure={name:'configure_spatial_view',description:'Set a review view, focus an existing room, or show and hide the replaceable furniture layer.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:MODES.map(m=>m.id)},room:{type:'string',enum:rooms.map(r=>r.id)},furniture:{type:'boolean'}},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Expected configuration object');const v=input as Record<string,unknown>;if(Object.keys(v).some(k=>!['mode','room','furniture'].includes(k))||('mode'in v&&!MODES.some(m=>m.id===v.mode))||('room'in v&&!rooms.some(r=>r.id===v.room))||('furniture'in v&&typeof v.furniture!=='boolean'))throw new Error('Invalid spatial view configuration');if(!stateRef.current.ready)throw new Error('The viewer is still loading');if(v.mode)setMode(v.mode as ViewMode);if(typeof v.furniture==='boolean')setOpts(p=>({...p,furniture:v.furniture as boolean}));await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));if(v.room){setSelected(v.room as string);api.current?.focusRoom(v.room as string)}await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {...stateRef.current};}};
  for(const tool of [read,configure]){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}
  return()=>lifecycle.abort();
 },[]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),5000);return()=>clearTimeout(t)},[message]);
 const choose=(id:string)=>{setSelected(id);api.current?.focusRoom(id)};
 const change=<K extends keyof ViewerOptions>(k:K,v:ViewerOptions[K])=>setOpts(p=>({...p,[k]:v}));
 const exportModel=async()=>{if(!api.current)return;setExporting(true);try{await api.current.exportGLB();setMessage('已导出完整高度模型，保留建筑层与设计层。')}catch{setMessage('导出未完成，请重试。')}finally{setExporting(false)}};
 return <main className="workspace">
 <header className="app-header"><div className="brand"><span className="brand-mark"><Box size={23}/></span><div><h1>BASE<span> / </span>空间母模型</h1><p>RESIDENTIAL SPATIAL STUDY</p></div></div><div className="project-status"><span className="status-dot"/>白模已建立<span className="divider"/>比例待实测</div><div className="header-actions"><Button variant="ghost" onClick={()=>setAnalysis(true)}><Info size={16}/>识图说明</Button><Button variant="outline" onClick={exportModel} disabled={!ready||exporting}><Download size={16}/>{exporting?'正在导出':'导出模型'}</Button></div></header>
 <div className={'work-body '+(!sidebar?'collapsed':'')}>
 <aside className="sidebar" aria-label="模型检查面板"><div className="panel-heading"><span>空间目录</span><span className="count">{rooms.length}</span><button title="收起侧栏" onClick={()=>setSidebar(false)}><PanelLeftClose size={16}/></button></div><div className="room-list">{rooms.filter(r=>!r.kind).map((r,i)=><button key={r.id} className={'room-item '+(selected===r.id?'selected':'')} onClick={()=>choose(r.id)}><span className="room-index">{(i+1).toString().padStart(2,'0')}</span><span>{r.name}</span><MoveUpRight size={13}/></button>)}<div className="room-divider">室外与公共空间</div>{rooms.filter(r=>r.kind).map(r=><button key={r.id} className={'room-item '+(selected===r.id?'selected':'')} onClick={()=>choose(r.id)}><span className="room-index">↗</span><span>{r.name}</span><MoveUpRight size={13}/></button>)}</div>
 <div className="layer-panel"><div className="section-label">MODEL LAYERS <span>模型分层</span></div><div className="fixed-layer"><LockKeyhole size={15}/><div>建筑结构层<small>墙体 · 楼板 · 门窗 · 固定边界</small></div><span>固定</span></div><label className="switch-row"><span>家具占位层<small>Interior Design Layer</small></span><Switch checked={opts.furniture} onCheckedChange={v=>change('furniture',v)} aria-label="显示家具占位层"/></label></div>
 <div className="styles-panel"><div className="section-label">DESIGN STYLE <span>设计方案</span></div><div className="style-grid"><button className="style active" onClick={()=>setMessage('当前为 BASE 白模。后续方案将整体替换家具、灯具、软装与材质。')}><span className="style-preview"><Box/></span><strong>BASE</strong><Check size={12}/></button>{['01','02','03'].map(n=><button key={n} className="style pending" onClick={()=>setMessage('STYLE '+n+' 尚未建立。提供参考图片后，将生成独立的整套室内设计层。')}><span className="style-preview">+</span><strong>STYLE {n}</strong><small>待添加</small></button>)}</div><p>固定建筑空间，整体替换室内方案。</p></div></aside>
 <section className="viewer-shell" aria-label="交互式空间 Viewer"><nav className="view-toolbar" aria-label="视图模式">{!sidebar&&<button title="展开空间目录" onClick={()=>setSidebar(true)}><PanelLeftOpen size={18}/></button>}<div className="view-tabs">{MODES.map(({id,title,label,icon:Icon})=><button key={id} title={title} className={mode===id?'active':''} onClick={()=>setMode(id)} aria-pressed={mode===id}><Icon size={16}/><span>{label}</span></button>)}</div><div className="white-pill"><span/>WHITE MODEL</div></nav>
 <div className="viewport"><div ref={host} className="canvas-host" style={{visibility:mode==='plan'?'hidden':'visible'}}/>{!ready&&mode!=='plan'&&<div className="load-state">{error||'正在构建基础空间…'}</div>}
 {mode==='plan'&&<FloorPlan selected={selected} select={choose} source={source} overlay={overlay} furnitureVisible={opts.furniture} showRoutes={opts.routes} labels={opts.labels}/>}
 <div className="view-title"><span className="eyebrow">BASE / 01</span><h2>{MODES.find(m=>m.id===mode)?.title}</h2><p>{mode==='walk'?'视高 1.60 m · 建筑边界碰撞已启用':mode==='plan'?'同坐标描摹 · 可叠加原始平面图':'基础空间母模型 · 无装修材质'}</p></div>
 {mode==='plan'?<div className="floating-options plan-options"><label className="switch-row"><span>原始图纸</span><Switch checked={source} onCheckedChange={setSource} aria-label="显示原始平面图"/></label><label className="range-label">原图叠加<span>{overlay}%</span><input aria-label="原图叠加透明度" type="range" min="0" max="100" value={overlay} onChange={e=>setOverlay(+e.target.value)}/></label></div>:<div className="floating-options">{([['labels','空间名称'],['routes','交通动线'],['ceiling','显示顶面'],['doors','开启平开门']] as const).map(([k,label])=><label className="switch-row" key={k}><span>{label}</span><Switch checked={opts[k]} onCheckedChange={v=>change(k,v)} aria-label={label}/></label>)}{mode!=='walk'&&<label className="range-label">墙体剖切<span>{opts.cut.toFixed(2)} m</span><input aria-label="墙体剖切高度" type="range" min="0.5" max="2.8" step="0.05" value={opts.cut} onChange={e=>change('cut',+e.target.value)}/></label>}</div>}
 <div className="orientation"><span>图纸上方</span><div>↑</div><small>非指北针</small></div>
 {current&&<div className="selection-card"><button className="close-selection" aria-label="取消空间选择" onClick={()=>setSelected('')}><X size={15}/></button><span className="eyebrow">SELECTED SPACE</span><h3>{current.name}<small>{current.en}</small></h3><p>{current.note}</p><div className="connections">连接 {current.connects.map(id=><button key={id} onClick={()=>choose(id)}>{rooms.find(r=>r.id===id)?.name}</button>)}</div></div>}
 {mode==='walk'&&<div className="walk-pad" aria-label="漫游移动控制">{([{key:'w',Icon:ArrowUp,label:'前进'},{key:'a',Icon:ArrowLeft,label:'左移'},{key:'s',Icon:ArrowDown,label:'后退'},{key:'d',Icon:ArrowRight,label:'右移'}]).map(({key,Icon,label})=><button key={key} className={'pad-'+key} aria-label={label} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);api.current?.key(key,true)}} onPointerUp={()=>api.current?.key(key,false)} onPointerCancel={()=>api.current?.key(key,false)}><Icon size={19}/></button>)}</div>}
 <div className="viewport-actions"><button title="重置视角" aria-label="重置视角" onClick={()=>api.current?.reset()}><RotateCcw size={18}/></button><button title="全屏" aria-label="全屏" onClick={()=>{const el=host.current?.closest('.viewer-shell');if(document.fullscreenElement)void document.exitFullscreen();else void el?.requestFullscreen().catch(()=>setMessage('此窗口不支持全屏，可收起侧栏扩大视图。'))}}><Maximize2 size={18}/></button></div></div>
 <footer className="viewer-footer"><span><span className="status-dot"/>{mode==='walk'?'拖动转向 · WASD / 方向键移动 · Shift 加速':mode==='plan'?'滚轮缩放 · 拖动平移 · 点击空间查看关系':'左键旋转 · 右键平移 · 滚轮缩放'}</span><span className="footer-scale"><Ruler size={14}/>1 px ≈ 14 mm<span className="divider"/>单位 m</span></footer></section></div>
 {message&&<div className="toast" role="status">{message}<button onClick={()=>setMessage('')} aria-label="关闭提示"><X size={15}/></button></div>}
 <Dialog open={analysis} onOpenChange={setAnalysis}><DialogContent className="analysis-modal" showCloseButton={false}><button className="modal-close" onClick={()=>setAnalysis(false)} aria-label="关闭识图说明"><X/></button><div className="eyebrow">DRAWING TO SPACE</div><DialogTitle>先固定空间，再展开设计。</DialogTitle><p>基于上传平面图逐点描摹。房间位置、交通关系、主要墙体与窗带保留原图逻辑；无标注尺寸不作为测量值。</p><img src="/source-plan.png" alt="用户提供的住宅户型原图"/><h3>识别结果</h3><p>三卧、两卫、衣帽间、厨房、餐厅、客厅、多功能区、玄关、储藏间、健身区、庭院、泳池，以及图右上方的公共前室、推定电梯井和楼梯。开放空间用功能边界标识，不增加隔墙。</p><h3>门窗与动线</h3><p>入户门连接前室与玄关。玄关向左进入餐厅，向下进入客厅；中央横向过道连接左侧卧室区，次卧（二）从客厅东北角进入。厨房向东开口，健身区从餐厅北侧进入。门扇、门洞与上方过梁分开建模，南侧与左侧弧形窗带保留。</p><h3>尺度与待确认项</h3><ul>{assumptions.map(s=><li key={s}>{s}</li>)}</ul><h3>可替换设计层</h3><p>建筑结构层包含墙体、柱垛占位、楼板、顶面、门窗、泳池和固定卫浴点位。床、沙发、桌椅、柜体、台面、器械和庭院家具属于独立设计层。后续方案通过独立设计层整体加载，建筑坐标保持不变。</p><Button variant="outline" onClick={()=>{const data={source:SOURCE,rooms,walls,openings,columns,furniture,footprint,assumptions};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='BASE-spatial-definition.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}><Download size={16}/>下载空间定义</Button></DialogContent></Dialog>
 </main>;
}
function FloorPlan({selected,select,source,overlay,furnitureVisible,showRoutes,labels}:{selected:string;select:(id:string)=>void;source:boolean;overlay:number;furnitureVisible:boolean;showRoutes:boolean;labels:boolean}){
 const [cam,setCam]=useState({x:0,y:0,k:1});const drag=useRef<{x:number;y:number;ox:number;oy:number}|null>(null),svgRef=useRef<SVGSVGElement>(null);
 return <div className="plan-stage"><svg ref={svgRef} viewBox="-80 -25 1400 1310" role="img" aria-label="按原图坐标重建的住宅二维平面图" onWheel={e=>setCam(p=>({...p,k:Math.min(4,Math.max(.5,p.k*(e.deltaY>0?.9:1.1)))}))} onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY,ox:cam.x,oy:cam.y};if(e.target===e.currentTarget)e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const d=drag.current;if(d){const k=1400/(svgRef.current?.clientWidth??1400);setCam(p=>({...p,x:d.ox+(e.clientX-d.x)*k,y:d.oy+(e.clientY-d.y)*k}))}}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}><g transform={`translate(${cam.x+627} ${cam.y+627}) scale(${cam.k}) translate(-627 -627)`}><polygon points={footprint.map(p=>p.join(',')).join(' ')} fill="white" stroke="#aab2b4" strokeWidth="1.5"/>
 {!source&&<><g>{rooms.map(r=><polygon key={r.id} points={r.boundary.map(p=>p.join(',')).join(' ')} fill={selected===r.id?'#d9e9e7':r.id==='pool'?'#e8eff0':'transparent'} stroke={selected===r.id?'#6b9892':'none'} strokeWidth="2" onClick={()=>select(r.id)}/>)}</g>{furnitureVisible&&furniture.map(f=><rect key={f.id} x={f.x-f.w/2} y={f.z-f.d/2} width={f.w} height={f.d} rx={['table','chair'].includes(f.kind)?8:2} fill="#f1f3f3" stroke="#b0b8ba" strokeWidth="1.5" pointerEvents="none"/>)}{walls.map(w=><line key={w.id} x1={w.a[0]} y1={w.a[1]} x2={w.b[0]} y2={w.b[1]} stroke={(w.h??2.8)<1?'#8e989d':'#424d54'} strokeWidth={w.t} strokeLinecap="square"/>)}{columns.map((c,i)=><polygon key={i} points={c.map(p=>p.join(',')).join(' ')} fill="#424d54"/>)}
 {openings.map(o=>{const [a,b]=[o.a,o.b],len=Math.hypot(b[0]-a[0],b[1]-a[1]);if(o.type==='door'){const h=o.hinge?b:a,end=o.hinge?a:b,dx=end[0]-h[0],dy=end[1]-h[1],sign=o.swing??1,open:Point=[h[0]+dy*sign,h[1]-dx*sign];return <g key={o.id} stroke={o.inferred?'#b2844e':'#78868b'} fill="none" strokeWidth="1.7"><line x1={h[0]} y1={h[1]} x2={open[0]} y2={open[1]}/><path d={`M${end.join(',')} A${len},${len} 0 0 ${sign>0?0:1} ${open.join(',')}`} strokeDasharray={o.inferred?'5 3':undefined}/></g>}return <g key={o.id} stroke={o.inferred?'#b2844e':'#64888f'} strokeWidth="3"><line x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]} strokeDasharray={o.type==='sliding'?'9 4':undefined}/><title>{o.name}{o.inferred?'（推定）':''}</title></g>})}
 {showRoutes&&routes.map((r,i)=><polyline key={i} points={r.map(p=>p.join(',')).join(' ')} stroke="#327c75" strokeWidth="3" strokeDasharray="8 5" fill="none"/>)}{labels&&rooms.map(r=><text key={r.id} x={r.center[0]} y={r.center[1]} textAnchor="middle" dominantBaseline="middle" fontSize="17" fontFamily="inherit" fill="#304049" stroke="white" strokeWidth="4" paintOrder="stroke" onClick={()=>select(r.id)} style={{cursor:'pointer'}}>{r.name}</text>)}</>}
 {(source||overlay>0)&&<image href="/source-plan.png" width="1254" height="1254" opacity={source?1:overlay/100} pointerEvents="none"/>}<g transform="translate(440,1240)"><line x1="0" y1="0" x2={2/SCALE} y2="0" stroke="#4a5d66" strokeWidth="3"/>{[0,1,2].map(i=><g key={i} transform={`translate(${i/SCALE},0)`}><line y1="-5" y2="5" stroke="#4a5d66"/><text y="23" fontSize="14" fill="#4a5d66">{i} m</text></g>)}</g></g></svg><div className="plan-legend"><span><i/>实体墙</span><span><i/>门窗</span><span><i/>推定边界</span><button onClick={()=>setCam({x:0,y:0,k:1})}>重置平面</button></div></div>
}
