
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {GTAOPass} from 'three/addons/postprocessing/GTAOPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {RectAreaLightUniformsLib} from 'three/addons/lights/RectAreaLightUniformsLib.js';
import {buildBase,pointInPolygon,segmentDistance} from './model';
import {buildDesign} from './design';
import {rooms,world,SCALE,footprint,type Point} from './plan';
import {CAMERAS,LIGHT_PRESETS,type StyleID,type DisplayMode,type Lighting,layout} from './design-data';

export type ViewMode='perspective'|'axon'|'top'|'plan'|'walk';
export type ViewerOptions={furniture:boolean;ceiling:boolean;labels:boolean;routes:boolean;doors:boolean;cut:number};
export type ViewerAPI=ReturnType<typeof createViewer>;
const spawn:Record<string,Point>={entry:[981,475],living:[885,865],flex:[528,921],dining:[909,553],kitchen:[600,537],bed1:[306,504],master:[296,991],wardrobe:[286,837],ensuite:[188,728],bath:[400,521],hall:[401,728],bed2:[1011,899],store:[1006,664],gym:[704,278],courtyard:[526,212],pool:[700,195],lobby:[992,287],lift:[991,271],stairs:[1130,393]};
export function createViewer(host:HTMLElement,onSelect:(id:string)=>void){
 RectAreaLightUniformsLib.init();
 const renderer=new T.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.localClippingEnabled=true;host.appendChild(renderer.domElement);renderer.domElement.tabIndex=0;
 const scene=new T.Scene();scene.background=new T.Color(0xe1e6e8);const model=buildBase();scene.add(model.root);const baseDesign=model.design;
 const cache=new Map<StyleID,ReturnType<typeof buildDesign>>();let currentDesign:ReturnType<typeof buildDesign>|null=null,style:StyleID='base',display:DisplayMode='arctic';
 const original=new WeakMap<T.Mesh,T.Material|T.Material[]>(),baseMaterials=new WeakMap<T.Mesh,T.Material|T.Material[]>();model.root.traverse(o=>{if(o instanceof T.Mesh){original.set(o,o.material);baseMaterials.set(o,o.material)}});
 const arctic=new T.MeshStandardMaterial({name:'ARCTIC_clay',color:0xc8cecf,roughness:.86}),arcticFloor=new T.MeshStandardMaterial({name:'ARCTIC_floor',color:0xaeb8bb,roughness:.95,side:T.DoubleSide}),arcticGlass=new T.MeshStandardMaterial({name:'ARCTIC_glass',color:0xc0d0d2,roughness:.3,transparent:true,opacity:.18,depthWrite:false,side:T.DoubleSide});
 const shadedCache=new Map<T.Material,T.Material>();
 const ambient=new T.HemisphereLight(0xe7edf0,0xadb5b4,.82);scene.add(ambient);scene.add(new T.AmbientLight(0xe7e1d5,.42));
 const sun=new T.DirectionalLight(0xfff6e6,2.55);sun.position.set(-9,20,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-12,right:12,top:12,bottom:-12,near:.4,far:60});sun.shadow.bias=-.0004;sun.shadow.normalBias=.018;sun.shadow.radius=3;scene.add(sun);scene.add(sun.target);
 const fill=new T.DirectionalLight(0xd9e6f3,.32);fill.position.set(10,8,-10);scene.add(fill);
 const ground=new T.Mesh(new T.PlaneGeometry(80,80),new T.MeshStandardMaterial({color:0xd2d9dc,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-1.42;ground.receiveShadow=true;ground.name='Presentation_ground';scene.add(ground);
 const perspective=new T.PerspectiveCamera(43,1,.04,150),ortho=new T.OrthographicCamera(-12,12,12,-12,.04,150);let camera:T.PerspectiveCamera|T.OrthographicCamera=perspective;
 let controls:OrbitControls=new OrbitControls(camera,renderer.domElement);
 let mode:ViewMode='perspective',options:ViewerOptions={furniture:true,ceiling:false,labels:true,routes:false,doors:true,cut:2.8},lighting={...LIGHT_PRESETS.ARCTIC};
 let width=1,height=1,disposed=false,frame=0,yaw=0,pitch=0,last=performance.now(),drag:{x:number;y:number}|null=null,activePreset='',lastInteraction=0,dirty=true;
 const envData=new Float32Array(128*64*4);for(let y=0;y<64;y++)for(let x=0;x<128;x++){const u=x/128,v=y/64,top=Math.pow(1-v,.65),soft=Math.exp(-Math.pow((u-.26)/.065,2)-Math.pow((v-.28)/.17,2))*2.4;const j=(y*128+x)*4;envData[j]=.30+top*.65+soft;envData[j+1]=.31+top*.69+soft;envData[j+2]=.32+top*.76+soft;envData[j+3]=1;}let environment:T.Texture|null=new T.DataTexture(envData,128,64,T.RGBAFormat,T.FloatType);environment.mapping=T.EquirectangularReflectionMapping;environment.needsUpdate=true;scene.environment=environment;let exportBusy=false;
 const keys=new Set<string>(),clip=new T.Plane(new T.Vector3(0,-1,0),2.8);
 const raycaster=new T.Raycaster(),pointer=new T.Vector2(),dragPlane=new T.Plane(new T.Vector3(0,1,0),0);let selectedAsset:T.Group|null=null,draggingAsset=false,dragOffset=new T.Vector3();
 const transform=new TransformControls(camera,renderer.domElement);transform.setMode('translate');transform.setSpace('world');transform.setSize(.78);transform.showY=false;scene.add(transform.getHelper());
 const undoStack:{id:string;position:[number,number,number];rotation:number}[][]=[],redoStack:{id:string;position:[number,number,number];rotation:number}[][]=[];
 const furnitureHint=document.createElement('div');furnitureHint.className='furniture-hint';furnitureHint.textContent='点击家具选择 · 红绿轴移动 · W 移动 / R 旋转 · Ctrl+Z 撤回 · Ctrl+Y 恢复';furnitureHint.style.display='none';host.appendChild(furnitureHint);
 const snapshot=()=>{const result:{id:string;position:[number,number,number];rotation:number}[]=[];model.design.traverse(o=>{if(o instanceof T.Group&&o.userData.kind)result.push({id:o.name,position:o.position.toArray(),rotation:o.rotation.y});});return result;};
 const restore=(snap:{id:string;position:[number,number,number];rotation:number}[])=>{const byId=new Map(snap.map(x=>[x.id,x]));model.design.traverse(o=>{if(o instanceof T.Group&&o.userData.kind){const s=byId.get(o.name);if(s){o.position.fromArray(s.position);o.rotation.y=s.rotation;}}});dirty=true;};
 const composer=new EffectComposer(renderer),renderPass=new RenderPass(scene,camera),ao=new GTAOPass(scene,camera,800,600),outputPass=new OutputPass();ao.blendIntensity=1.15;ao.updateGtaoMaterial({radius:.35,distanceExponent:1.4,thickness:.5,samples:12});ao.updatePdMaterial({radius:5,samples:12});composer.addPass(renderPass);composer.addPass(ao);composer.addPass(outputPass);
 const labels=rooms.map(r=>{const el=document.createElement('button');el.className='room-label';el.textContent=r.name;el.addEventListener('pointerdown',e=>e.stopPropagation());el.addEventListener('click',()=>onSelect(r.id));host.appendChild(el);return {el,room:r};});
 function resize(){width=host.clientWidth||800;height=host.clientHeight||600;renderer.setSize(width,height);composer.setSize(width,height);perspective.aspect=width/height;perspective.updateProjectionMatrix();const half=11.4;ortho.left=-half*width/height;ortho.right=half*width/height;ortho.top=half;ortho.bottom=-half;ortho.updateProjectionMatrix();dirty=true;}
 const observer=new ResizeObserver(resize);observer.observe(host);
 function newControls(){controls.dispose();controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.maxPolarAngle=Math.PI*.495;controls.minDistance=.25;controls.maxDistance=65;controls.minZoom=.35;controls.maxZoom=8;controls.enabled=mode!=='walk'&&mode!=='plan';controls.enableRotate=mode!=='top';controls.addEventListener('change',()=>{dirty=true;lastInteraction=performance.now()});}
 function reset(){activePreset='';if(mode==='walk'){const p=world(spawn.entry);perspective.position.set(p[0],1.6,p[1]);yaw=Math.PI/2;pitch=0;dirty=true;return;}camera.up.set(0,1,0);controls.target.set(0,0,.1);perspective.fov=43;if(mode==='top'){ortho.zoom=1;ortho.position.set(0,30,.101);ortho.up.set(0,0,-1);}else if(mode==='axon'){ortho.zoom=1.05;ortho.position.set(16,21,24)}else{perspective.position.set(15.7,21.3,26)}camera.lookAt(controls.target);camera.updateProjectionMatrix();controls.update();dirty=true;}
 function updateAOCamera(){renderPass.camera=camera;ao.camera=camera;ao.gtaoMaterial.defines.PERSPECTIVE_CAMERA=camera instanceof T.PerspectiveCamera?1:0;ao.gtaoMaterial.needsUpdate=true;}
 function setMode(next:ViewMode){if(next===mode)return;mode=next;keys.clear();camera=next==='axon'||next==='top'?ortho:perspective;transform.camera=camera;updateAOCamera();newControls();reset();setOptions(options);renderer.domElement.setAttribute('aria-label',next==='walk'?'第一人称漫游。拖动转向，WASD 移动':'3D 空间。拖动旋转，右键平移，滚轮缩放');}
 function applyDisplay(){renderer.shadowMap.needsUpdate=true;
  model.root.traverse(o=>{if(o instanceof T.Mesh){const src=original.get(o)??o.material;original.set(o,src);if(display==='material'){o.material=src;}else if(display==='arctic'){const m=Array.isArray(src)?src[0]:src;o.material=(m as T.MeshStandardMaterial).transparent?arcticGlass:/floor|finish|rug|ground|basin_bottom/i.test(o.name)?arcticFloor:arctic;}else{const convert=(mat:T.Material)=>{if(!shadedCache.has(mat)){const next=mat.clone() as T.MeshStandardMaterial;next.map=null;next.bumpMap=null;next.normalMap=null;next.roughnessMap=null;next.metalnessMap=null;if(mat.userData.baseColor)next.color.set(mat.userData.baseColor);next.roughness=.73;next.metalness=Math.min(next.metalness,.15);next.emissiveIntensity=0;shadedCache.set(mat,next)}return shadedCache.get(mat)!};o.material=Array.isArray(src)?src.map(convert):convert(src)}}
   if(o instanceof T.LineSegments){o.visible=lighting.edges>0;const m=o.material as T.LineBasicMaterial;m.opacity=lighting.edges;}
   if(o instanceof T.RectAreaLight)o.visible=display==='material';
  });scene.environmentIntensity=lighting.ambient*(display==='arctic'?.24:1.5);dirty=true;
 }
 function setDisplay(next:DisplayMode){display=next;applyDisplay();}
 function applyArchitectureFinish(){const p=currentDesign?.palette;model.architecture.traverse(o=>{if(!(o instanceof T.Mesh))return;let mat=baseMaterials.get(o)??o.material;if(p){if(/Pool|pool/i.test(o.name))mat=p.pool;else if(/floor|ceiling|Stair_tread/i.test(o.name))mat=/ceiling/i.test(o.name)?p.wall:p.ground;else if(/glass|Shower_screen/.test(o.name))mat=p.glass;else if(/jamb|mullion|head$|bottom$|handrail|riser|Handle|Tap/.test(o.name))mat=p.metal;else if(/Bowl|Basin|Cistern|Seat|Shower_tray/.test(o.name))mat=p.white;else if(/Hob/.test(o.name))mat=p.dark;else if(o.parent?.parent===model.doors)mat=p.wood;else mat=p.wall;}original.set(o,mat)});}
 function setStyle(next:StyleID){if(style===next)return;style=next;model.root.remove(model.design);if(next==='base'){currentDesign=null;model.design=baseDesign;}else{if(!cache.has(next))cache.set(next,buildDesign(next));currentDesign=cache.get(next)!;model.design=currentDesign.group;model.design.traverse(o=>{if(o instanceof T.Mesh&&!original.has(o))original.set(o,o.material)});}model.root.add(model.design);model.design.visible=options.furniture;applyArchitectureFinish();applyDisplay();dirty=true;}
 function setLighting(next:Lighting){lighting={...next};const azi=next.azimuth*Math.PI/180,ele=next.elevation*Math.PI/180;sun.position.set(Math.sin(azi)*24*Math.cos(ele),24*Math.sin(ele),Math.cos(azi)*24*Math.cos(ele));sun.shadow.intensity=next.shadow;sun.castShadow=next.shadow>0;ambient.intensity=next.ambient;fill.intensity=next.ambient*.25;ao.enabled=next.ao>0;ao.blendIntensity=next.ao;scene.environmentIntensity=next.ambient*(display==='arctic'?.24:1.5);applyDisplay();dirty=true;}
 function setOptions(next:ViewerOptions){renderer.shadowMap.needsUpdate=true;options={...next};model.design.visible=next.furniture;model.ceiling.visible=next.ceiling;model.routeGroup.visible=next.routes;model.setDoors(next.doors);clip.constant=next.cut;renderer.clippingPlanes=mode==='walk'||next.cut>=2.8?[]:[clip];dirty=true;}
 function valid(p:Point){if(!pointInPolygon(p,footprint))return false;if(pointInPolygon(p,rooms.find(r=>r.id==='pool')!.boundary))return false;if(p[0]>1098&&p[1]>445&&p[1]<751)return false;const radius=12;for(const c of model.collisions){if(c.door)continue;if(segmentDistance(p,c.a,c.b)<c.t/2+radius)return false;}
  if(!options.doors){for(const d of model.doorPivots){const hinge=d.pivot.position,px=hinge.x/SCALE+627,pz=hinge.z/SCALE+627,leaf=d.pivot.children[0] as T.Mesh,len=((leaf.geometry as T.BoxGeometry).parameters.width+.04)/SCALE,end:Point=[px+Math.cos(d.angle)*len,pz-Math.sin(d.angle)*len];if(segmentDistance(p,[px,pz],end)<radius+2)return false;}}
  if(options.furniture){for(const b of currentDesign?.colliders??model.obstacleBoxes){if(Math.abs(p[0]-b.x)<b.w/2+radius&&Math.abs(p[1]-b.z)<b.d/2+radius)return false;}}return true;}
 function focusRoom(id:string){const room=rooms.find(r=>r.id===id);if(!room)return;if(mode==='walk'){let p=spawn[id]??room.center;if(!valid(p)){const pts:Point[]=[];for(let x=-70;x<=70;x+=10)for(let z=-70;z<=70;z+=10)pts.push([p[0]+x,p[1]+z]);const found=pts.sort((a,b)=>Math.hypot(a[0]-p[0],a[1]-p[1])-Math.hypot(b[0]-p[0],b[1]-p[1])).find(q=>valid(q)&&pointInPolygon(q,room.boundary));if(found)p=found;else return;}const [x,z]=world(p);perspective.position.set(x,1.6,z);yaw=0;pitch=0;}else if(mode!=='plan'){const [x,z]=world(room.center),shift=new T.Vector3(x,0,z).sub(controls.target);camera.position.add(shift);controls.target.set(x,0,z);controls.update();}dirty=true;}
 function setPreset(id:string){const p=CAMERAS.find(p=>p.id===id);if(!p)return;if(mode!=='perspective'){setMode('perspective')}activePreset=id;const [x,z]=world([p.position[0],p.position[2]]),[tx,tz]=world([p.target[0],p.target[2]]);perspective.position.set(x,p.position[1],z);perspective.up.set(0,1,0);perspective.fov=p.fov;perspective.aspect=width/height;perspective.updateProjectionMatrix();controls.target.set(tx,p.target[1],tz);perspective.lookAt(controls.target);controls.update();dirty=true;}
 function key(k:string,pressed:boolean){if(pressed)keys.add(k.toLowerCase());else keys.delete(k.toLowerCase())}
 const down=(e:KeyboardEvent)=>{if(mode!=='walk'||(e.target as HTMLElement).matches('input,textarea'))return;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','shift'].includes(e.key.toLowerCase())){e.preventDefault();key(e.key,true)}};
 const up=(e:KeyboardEvent)=>key(e.key,false),blur=()=>keys.clear();window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);
 const pdown=(e:PointerEvent)=>{if(mode==='walk'){drag={x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId);renderer.domElement.focus()}};
 const pmove=(e:PointerEvent)=>{if(mode==='walk'&&drag){yaw-=(e.clientX-drag.x)*.004;pitch=Math.max(-1.35,Math.min(1.35,pitch-(e.clientY-drag.y)*.004));drag={x:e.clientX,y:e.clientY};dirty=true}};const pup=()=>drag=null;
 const furniturePointer=(e:PointerEvent)=>{if(mode==='walk'||mode==='plan'||!options.furniture||transform.dragging)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-((e.clientY-rect.top)/rect.height)*2+1);raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObject(model.design,true);const hit=hits.find(h=>{let n=h.object as T.Object3D;while(n&&n!==model.design){if(n.userData.kind)return true;n=n.parent!;}return false});if(!hit)return;let n=hit.object as T.Object3D;while(n.parent&&n.parent!==model.design&&!n.userData.kind)n=n.parent;selectedAsset=n as T.Group;transform.attach(selectedAsset);furnitureHint.style.display='block';furnitureHint.textContent=`${selectedAsset.userData.kind??'家具'} · 红绿轴移动 · W 移动 / R 旋转 · Ctrl+Z 撤回 · Ctrl+Y 恢复`;undoStack.push(snapshot());redoStack.length=0;dirty=true;};
 const furnitureMove=(e:PointerEvent)=>{if(transform.dragging)return;if(!draggingAsset||!selectedAsset)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-((e.clientY-rect.top)/rect.height)*2+1);raycaster.setFromCamera(pointer,camera);const p=new T.Vector3();if(raycaster.ray.intersectPlane(dragPlane,p)){selectedAsset.position.x=p.x+dragOffset.x;selectedAsset.position.z=p.z+dragOffset.z;dirty=true;}};
 const furnitureUp=()=>{draggingAsset=false;};
 const furnitureKey=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();const prev=undoStack.pop();if(prev){redoStack.push(snapshot());restore(prev);}return;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();const next=redoStack.pop();if(next){undoStack.push(snapshot());restore(next);}return;}if(!selectedAsset||mode==='walk')return;if(e.key.toLowerCase()==='w'){transform.setMode('translate');furnitureHint.textContent='移动模式 · 红绿轴移动 · R 切换旋转';}else if(e.key.toLowerCase()==='r'){transform.setMode('rotate');furnitureHint.textContent='旋转模式 · 红绿轴旋转 · W 切换移动';}else if(e.key==='Escape'){transform.detach();selectedAsset=null;furnitureHint.style.display='none';dirty=true;}};
 transform.addEventListener('dragging-changed',(e:any)=>{controls.enabled=!e.value;dirty=true;});transform.addEventListener('mouseDown',()=>{undoStack.push(snapshot());redoStack.length=0;});transform.addEventListener('objectChange',()=>{dirty=true;});
 renderer.domElement.addEventListener('pointerdown',pdown);renderer.domElement.addEventListener('pointermove',pmove);renderer.domElement.addEventListener('pointerup',pup);renderer.domElement.addEventListener('pointercancel',pup);renderer.domElement.addEventListener('pointerdown',furniturePointer);renderer.domElement.addEventListener('pointermove',furnitureMove);renderer.domElement.addEventListener('pointerup',furnitureUp);window.addEventListener('keydown',furnitureKey);
 function animate(now:number){if(disposed)return;const dt=Math.min((now-last)/1000,.04);last=now;
  if(mode==='walk'){const f=Number(keys.has('w')||keys.has('arrowup'))-Number(keys.has('s')||keys.has('arrowdown')),s=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft'));const speed=(keys.has('shift')?2.5:1.4)*dt/Math.max(1,Math.hypot(f,s)),dx=(-Math.sin(yaw)*f+Math.cos(yaw)*s)*speed,dz=(-Math.cos(yaw)*f-Math.sin(yaw)*s)*speed;const x=perspective.position.x,z=perspective.position.z;if(valid([(x+dx)/SCALE+627,z/SCALE+627]))perspective.position.x+=dx;if(valid([perspective.position.x/SCALE+627,(z+dz)/SCALE+627]))perspective.position.z+=dz;perspective.quaternion.setFromEuler(new T.Euler(pitch,yaw,0,'YXZ'));perspective.position.y=1.6;if(f||s)dirty=true;
  }else controls.update();
  labels.forEach(({el,room})=>{const [x,z]=world(room.center),v=new T.Vector3(x,.2,z).project(camera);const show=options.labels&&!activePreset&&mode!=='walk'&&mode!=='plan'&&v.z<1&&v.z>-1&&Math.abs(v.x)<.99&&Math.abs(v.y)<.98;el.style.display=show?'block':'none';if(show){el.style.left=(v.x*.5+.5)*width+'px';el.style.top=(-v.y*.5+.5)*height+'px'}});
  if(mode!=='plan'&&(dirty||now-lastInteraction<650)){composer.render();dirty=false;}
  frame=requestAnimationFrame(animate);
 }
 function state(){return {style,display,mode,preset:activePreset,options:{...options},lighting:{...lighting},camera:{position:camera.position.toArray(),quaternion:camera.quaternion.toArray(),fov:camera instanceof T.PerspectiveCamera?camera.fov:null,aspect:width/height},assets:layout(style).length,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles};}
 function savePNG(){composer.render();const a=document.createElement('a');a.href=renderer.domElement.toDataURL('image/png');a.download=`${style}-${activePreset||mode}-model.png`;a.click();return true;}
 async function exportGLB(){if(exportBusy)return;exportBusy=true;try{const originals:T.Object3D[]=[];model.root.traverse(o=>originals.push(o));const exportRoot=model.root.clone(true);let index=0;exportRoot.traverse(o=>{const src=originals[index++];if(o instanceof T.Mesh&&src instanceof T.Mesh){o.material=original.get(src)??src.material;}o.visible=true;if(o.name==='03_REVIEW_ANNOTATIONS')o.visible=false});const data=await new GLTFExporter().parseAsync(exportRoot,{binary:true,onlyVisible:true});const url=URL.createObjectURL(new Blob([data as ArrayBuffer],{type:'model/gltf-binary'}));const a=document.createElement('a');a.href=url;a.download=`${style}-residence-layered.glb`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}finally{exportBusy=false}}
 newControls();resize();reset();applyDisplay();setLighting(lighting);frame=requestAnimationFrame(animate);
 return {setMode,setOptions,focusRoom,setPreset,reset,key,exportGLB,setStyle,setDisplay,setLighting,savePNG,state,dispose(){disposed=true;cancelAnimationFrame(frame);observer.disconnect();controls.dispose();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);labels.forEach(l=>l.el.remove());environment?.dispose();const geometries=new Set<T.BufferGeometry>(),materials=new Set<T.Material>(),textures=new Set<T.Texture>();const collect=(root:T.Object3D)=>root.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Line){geometries.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));if(o instanceof T.Mesh){const src=original.get(o);if(src)(Array.isArray(src)?src:[src]).forEach(m=>materials.add(m))}}});collect(scene);collect(baseDesign);cache.forEach(c=>collect(c.group));shadedCache.forEach(m=>materials.add(m));materials.forEach(m=>{const v=m as T.MeshStandardMaterial;[v.map,v.bumpMap,v.normalMap].forEach(t=>{if(t)textures.add(t)});m.dispose()});textures.forEach(t=>t.dispose());geometries.forEach(g=>g.dispose());composer.dispose();ao.dispose();arctic.dispose();arcticFloor.dispose();arcticGlass.dispose();renderer.dispose();renderer.domElement.remove();}};
}




