import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {buildBase,pointInPolygon,segmentDistance} from './model';
import {rooms,world,SCALE,footprint, type Point} from './plan';
export type ViewMode='perspective'|'axon'|'top'|'plan'|'walk';
export type ViewerOptions={furniture:boolean;ceiling:boolean;labels:boolean;routes:boolean;doors:boolean;cut:number};
export type ViewerAPI=ReturnType<typeof createViewer>;
const spawn:Record<string,Point>={entry:[983,481],living:[885,860],flex:[528,841],dining:[908,553],kitchen:[596,536],bed1:[306,504],master:[294,991],wardrobe:[286,837],ensuite:[188,728],bath:[404,529],hall:[401,728],bed2:[1011,897],store:[1006,664],gym:[703,278],courtyard:[526,252],pool:[700,195],lobby:[992,287],lift:[991,271],stairs:[1130,393]};
export function createViewer(host:HTMLElement,onSelect:(id:string)=>void){
 const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;renderer.localClippingEnabled=true;host.appendChild(renderer.domElement);renderer.domElement.tabIndex=0;
 const scene=new T.Scene();const model=buildBase();scene.add(model.root);
 const ambient=new T.HemisphereLight(0xffffff,0xc0cbd0,2.4);scene.add(ambient);
 const sun=new T.DirectionalLight(0xffffff,3.1);sun.position.set(-9,20,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-13,right:13,top:13,bottom:-13,near:.5,far:55});sun.shadow.bias=-.0006;sun.shadow.normalBias=.025;sun.shadow.radius=3;scene.add(sun);
 const fill=new T.DirectionalLight(0xeaf3ff,1);fill.position.set(10,8,-10);scene.add(fill);
 const ground=new T.Mesh(new T.PlaneGeometry(160,160),new T.ShadowMaterial({opacity:.10}));ground.rotation.x=-Math.PI/2;ground.position.y=-1.4;ground.receiveShadow=true;scene.add(ground);
 const perspective=new T.PerspectiveCamera(43,1,.05,200),ortho=new T.OrthographicCamera(-12,12,12,-12,.05,200);let camera:T.PerspectiveCamera|T.OrthographicCamera=perspective;
 let controls:OrbitControls<T.PerspectiveCamera|T.OrthographicCamera>=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.09;controls.maxPolarAngle=Math.PI*.49;controls.minDistance=2;controls.maxDistance=65;
 let mode:ViewMode='perspective',options:ViewerOptions={furniture:true,ceiling:false,labels:true,routes:false,doors:true,cut:2.8};let width=1,height=1,disposed=false,frame=0,yaw=0,pitch=0,last=performance.now(),drag:{x:number;y:number}|null=null;
 const keys=new Set<string>();const clip=new T.Plane(new T.Vector3(0,-1,0),2.8);
 const labels=rooms.map(r=>{const el=document.createElement('button');el.className='room-label';el.textContent=r.name;el.addEventListener('pointerdown',e=>e.stopPropagation());el.addEventListener('click',()=>{onSelect(r.id);focusRoom(r.id)});host.appendChild(el);return {el,room:r};});
 function resize(){width=host.clientWidth||800;height=host.clientHeight||600;renderer.setSize(width,height);perspective.aspect=width/height;perspective.updateProjectionMatrix();const half=11.8;ortho.left=-half*width/height;ortho.right=half*width/height;ortho.top=half;ortho.bottom=-half;ortho.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(host);resize();
 function newControls(){controls.dispose();controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.09;controls.maxPolarAngle=Math.PI*.49;controls.minDistance=2;controls.maxDistance=65;controls.minZoom=.35;controls.maxZoom=8;controls.enabled=mode!=='walk'&&mode!=='plan';controls.enableRotate=mode!=='top';}
 function reset(){if(mode==='walk'){const p=world(spawn.entry);perspective.position.set(p[0],1.6,p[1]);yaw=0;pitch=0;return;}camera.up.set(0,1,0);controls.target.set(0,0,.2);if(mode==='top'){ortho.zoom=1;ortho.position.set(0,30,.201);ortho.up.set(0,0,-1);}else if(mode==='axon'){ortho.zoom=1.05;ortho.position.set(16,21,24)}else{perspective.position.set(15.7,21.3,26)}camera.lookAt(controls.target);camera.updateProjectionMatrix();controls.update();}
 function setMode(next:ViewMode){mode=next;keys.clear();camera=next==='axon'||next==='top'?ortho:perspective;newControls();reset();setOptions(options);renderer.domElement.setAttribute('aria-label',next==='walk'?'第一人称漫游。拖动转向，WASD 移动':'3D 空间。拖动旋转，右键平移，滚轮缩放');}
 function setOptions(next:ViewerOptions){options=next;model.design.visible=next.furniture;model.ceiling.visible=next.ceiling;model.routeGroup.visible=next.routes;model.setDoors(next.doors);clip.constant=next.cut;renderer.clippingPlanes=mode==='walk'||next.cut>=2.8?[]:[clip];}
 function valid(p:Point){if(!pointInPolygon(p,footprint))return false;if(pointInPolygon(p,rooms.find(r=>r.id==='pool')!.boundary))return false;if(p[0]>1098&&p[1]>445&&p[1]<751)return false;const radius=12;for(const c of model.collisions){if(c.door)continue; if(segmentDistance(p,c.a,c.b)<c.t/2+radius)return false;}if(!options.doors){for(const d of model.doorPivots){const hinge=d.pivot.position,px=hinge.x/SCALE+627,pz=hinge.z/SCALE+627;const leaf=d.pivot.children[0] as T.Mesh;const len=((leaf.geometry as T.BoxGeometry).parameters.width+.04)/SCALE;const end:Point=[px+Math.cos(d.angle)*len,pz-Math.sin(d.angle)*len];if(segmentDistance(p,[px,pz],end)<radius+2)return false;}}
  if(options.furniture){for(const b of model.obstacleBoxes){if(Math.abs(p[0]-b.x)<b.w/2+radius&&Math.abs(p[1]-b.z)<b.d/2+radius)return false;}}return true;}
 function focusRoom(id:string){const room=rooms.find(r=>r.id===id);if(!room)return;if(mode==='walk'){let p=spawn[id]??room.center;if(!valid(p)){const pts:Point[]=[];for(let x=-70;x<=70;x+=10)for(let z=-70;z<=70;z+=10)pts.push([p[0]+x,p[1]+z]);const found=pts.sort((a,b)=>Math.hypot(a[0]-p[0],a[1]-p[1])-Math.hypot(b[0]-p[0],b[1]-p[1])).find(q=>valid(q)&&pointInPolygon(q,room.boundary));if(found)p=found;else return;}const [x,z]=world(p);perspective.position.set(x,1.6,z);yaw=0;pitch=0;}else if(mode!=='plan'){const [x,z]=world(room.center);const shift=new T.Vector3(x,0,z).sub(controls.target);camera.position.add(shift);controls.target.set(x,0,z);controls.update();}}
 function key(k:string,pressed:boolean){if(pressed)keys.add(k.toLowerCase());else keys.delete(k.toLowerCase())}
 const down=(e:KeyboardEvent)=>{if(mode!=='walk'||(e.target as HTMLElement).matches('input,textarea'))return;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','shift'].includes(e.key.toLowerCase())){e.preventDefault();key(e.key,true)}};
 const up=(e:KeyboardEvent)=>key(e.key,false),blur=()=>keys.clear();window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);
 const pdown=(e:PointerEvent)=>{if(mode==='walk'){drag={x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId);renderer.domElement.focus()}};
 const pmove=(e:PointerEvent)=>{if(mode==='walk'&&drag){yaw-=(e.clientX-drag.x)*.004;pitch=Math.max(-1.35,Math.min(1.35,pitch-(e.clientY-drag.y)*.004));drag={x:e.clientX,y:e.clientY}}};const pup=()=>drag=null;
 renderer.domElement.addEventListener('pointerdown',pdown);renderer.domElement.addEventListener('pointermove',pmove);renderer.domElement.addEventListener('pointerup',pup);renderer.domElement.addEventListener('pointercancel',pup);
 function animate(now:number){if(disposed)return;const dt=Math.min((now-last)/1000,.045);last=now;if(mode==='walk'){
  const f=Number(keys.has('w')||keys.has('arrowup'))-Number(keys.has('s')||keys.has('arrowdown')),s=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft'));const speed=(keys.has('shift')?2.8:1.55)*dt/Math.max(1,Math.hypot(f,s));const dx=(-Math.sin(yaw)*f+Math.cos(yaw)*s)*speed,dz=(-Math.cos(yaw)*f-Math.sin(yaw)*s)*speed;
  const x=perspective.position.x,z=perspective.position.z;const testX:Point=[(x+dx)/SCALE+627,z/SCALE+627];if(valid(testX))perspective.position.x+=dx;const testZ:Point=[perspective.position.x/SCALE+627,(z+dz)/SCALE+627];if(valid(testZ))perspective.position.z+=dz;
  perspective.quaternion.setFromEuler(new T.Euler(pitch,yaw,0,'YXZ'));perspective.position.y=1.6;
 }else controls.update();
 labels.forEach(({el,room})=>{const [x,z]=world(room.center);const v=new T.Vector3(x,.2,z).project(camera);const show=options.labels&&mode!=='walk'&&mode!=='plan'&&v.z<1&&v.z>-1&&Math.abs(v.x)<.99&&Math.abs(v.y)<.98;el.style.display=show?'block':'none';if(show){el.style.left=(v.x*.5+.5)*width+'px';el.style.top=(-v.y*.5+.5)*height+'px'}});
 if(mode!=='plan')renderer.render(scene,camera);frame=requestAnimationFrame(animate);}
 reset();frame=requestAnimationFrame(animate);
 async function exportGLB(){const exportRoot=model.root.clone(true);exportRoot.traverse(o=>{o.visible=true;if(o.name==='03_REVIEW_ANNOTATIONS')o.visible=false});const data=await new GLTFExporter().parseAsync(exportRoot,{binary:true,onlyVisible:true});const url=URL.createObjectURL(new Blob([data as ArrayBuffer],{type:'model/gltf-binary'}));const a=document.createElement('a');a.href=url;a.download='BASE-residence-layered.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
 return {setMode,setOptions,focusRoom,reset,key,exportGLB,dispose(){disposed=true;cancelAnimationFrame(frame);observer.disconnect();controls.dispose();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);labels.forEach(l=>l.el.remove());scene.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.LineSegments||o instanceof T.Line){o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.dispose())}});renderer.dispose();renderer.domElement.remove();}};
}
