'use client';
import {Camera,Check,ChevronDown,Download,Image as ImageIcon,Sun,Box,SlidersHorizontal} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {NativeSelect} from '@/components/ui/native-select';
import {STYLES,CAMERAS,LIGHT_PRESETS,type StyleID,type DisplayMode,type Lighting} from '@/lib/spatial/design-data';

export function StylePicker({style,onChange,onInfo}:{style:StyleID;onChange:(id:StyleID)=>void;onInfo:()=>void}){
 return <div className="scheme-picker"><div className="section-label">DESIGN STYLE <button onClick={onInfo}>参考与设计</button></div><div className="scheme-list">{STYLES.map(s=><button key={s.id} className={'scheme '+(s.id===style?'active':'')} onClick={()=>onChange(s.id)} aria-pressed={style===s.id}><span className="scheme-swatches">{s.colors.map(c=><i key={c} style={{background:c}}/>)}</span><span><b>{s.label}</b><small>{s.name}</small></span>{style===s.id&&<Check size={14}/>}</button>)}</div><p className="scheme-hint">切换整套家具与设计，保留当前镜头。</p></div>
}
export function ComparisonBar({style,preset,display,onDisplay,onPreset,onSave}:{style:StyleID;preset:string;display:DisplayMode;onDisplay:(v:DisplayMode)=>void;onPreset:(id:string)=>void;onSave:()=>void}){
 return <div className="comparison-bar"><div className="camera-select"><Camera size={16}/><NativeSelect value={preset} onChange={e=>onPreset(e.target.value)} aria-label="固定空间机位"><option value="">整体 / 自由视角</option>{CAMERAS.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</NativeSelect></div><div className="display-tabs" aria-label="显示模式">{(['arctic','shaded','material'] as DisplayMode[]).map(m=><button key={m} className={display===m?'active':''} onClick={()=>onDisplay(m)} aria-pressed={display===m}>{m.toUpperCase()}</button>)}</div><button className="save-image" title="保存当前画面 PNG" aria-label="保存当前画面 PNG" onClick={onSave}><Download size={17}/></button></div>
}
export function LightingPanel({value,onChange}:{value:Lighting;onChange:(v:Lighting)=>void}){
 return <details className="lighting-panel"><summary><Sun size={15}/><span>光影 / LIGHTING</span><ChevronDown size={14}/></summary><div className="lighting-content"><div className="lighting-presets">{Object.entries(LIGHT_PRESETS).map(([name,p])=><button key={name} className={JSON.stringify(p)===JSON.stringify(value)?'active':''} onClick={()=>onChange({...p})}>{name}</button>)}</div>{([{key:'azimuth',label:'主光方向',min:0,max:360,step:5,unit:'°'},{key:'elevation',label:'主光高度',min:10,max:85,step:1,unit:'°'},{key:'shadow',label:'阴影强度',min:0,max:1,step:.05},{key:'ambient',label:'环境光',min:.1,max:2,step:.05},{key:'ao',label:'AO 接触暗部',min:0,max:2,step:.05},{key:'edges',label:'细微轮廓',min:0,max:.4,step:.01}] as const).map(c=><label className="lighting-range" key={c.key}><span>{c.label}<b>{value[c.key].toFixed(c.key==='azimuth'||c.key==='elevation'?0:2)}{'unit'in c?c.unit:''}</b></span><Slider value={[value[c.key]]} min={c.min} max={c.max} step={c.step} onValueChange={v=>onChange({...value,[c.key]:Array.isArray(v)?v[0]:v})} aria-label={c.label}/></label>)}<p>调整方向与接触暗部，检查墙体、家具和柜体的几何关系。</p></div></details>
}
export function DesignNotes({style}:{style:StyleID}){
 const s=STYLES.find(s=>s.id===style)!;return <div className="design-notes"><div className="reference-palette">{s.colors.map(c=><span key={c} style={{background:c}}/>)}</div><h3>{s.label} · {s.name}</h3><p>{s.summary}</p>{s.reference&&<img src={s.reference} alt={s.name+'用户提供的完整参考板'}/>}<h3>家具与空间构图</h3><p>{s.geometry}</p><h3>材质体系</h3><p>{s.material}</p><h3>灯具与光线</h3><p>{s.lighting}</p><h3>全屋延伸</h3><p>玄关保留主通道，组合收纳、镜面与换鞋凳；多功能区配置工作桌、阅读椅与展示架。三间卧室分别落实床、床头柜、灯具、背景板、地毯和窗帘。厨房与卫浴保持原有湿区点位，替换柜体、台面、镜面及灯具。庭院采用对应的户外座具和种植，池畔保留跑步及力量训练设备。</p><h3>模型细节与同机位比较</h3><p>三套方案均包含独立家具几何、灯具、窗帘、靠垫、披毯、床品和桌面软装。切换 ARCTIC 可隐藏材质，直接比较家具造型；切换风格保留镜头。模型为中等精度设计表达，并非家具厂商的产品数字模型。</p></div>;
}
